CREATE TABLE IF NOT EXISTS `ip_challenge_runs` (
  `guid` INT UNSIGNED NOT NULL,
  `tier` TINYINT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `picked_flags` INT UNSIGNED NOT NULL DEFAULT 0,
  `failed_flags` INT UNSIGNED NOT NULL DEFAULT 0,
  `successful_flags` INT UNSIGNED NOT NULL DEFAULT 0,
  `started_at` INT UNSIGNED NOT NULL DEFAULT 0,
  `ended_at` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`guid`, `tier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
