CREATE TABLE IF NOT EXISTS `ip_permadeath` (
  `guid` INT UNSIGNED NOT NULL,
  `is_dead` TINYINT(1) NOT NULL DEFAULT 0,
  `death_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `death_map` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `death_x` FLOAT NOT NULL DEFAULT 0,
  `death_y` FLOAT NOT NULL DEFAULT 0,
  `death_z` FLOAT NOT NULL DEFAULT 0,
  `death_o` FLOAT NOT NULL DEFAULT 0,
  `death_reason` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
